C:\Users\prave\Desktop\HealthTrackerjava\src\AddDoctorPassword.java
C:\Users\prave\Desktop\HealthTrackerjava\src\CheckP122.java
C:\Users\prave\Desktop\HealthTrackerjava\src\CheckSchema.java
C:\Users\prave\Desktop\HealthTrackerjava\src\CheckTables.java
C:\Users\prave\Desktop\HealthTrackerjava\src\FixSchema.java
C:\Users\prave\Desktop\HealthTrackerjava\src\Main.java
C:\Users\prave\Desktop\HealthTrackerjava\src\TestDB.java
C:\Users\prave\Desktop\HealthTrackerjava\src\TestInsert.java
C:\Users\prave\Desktop\HealthTrackerjava\src\TestServiceRecord.java
C:\Users\prave\Desktop\HealthTrackerjava\src\UpdateSchema.java
C:\Users\prave\Desktop\HealthTrackerjava\src\backend\dao\AdminDAO.java
C:\Users\prave\Desktop\HealthTrackerjava\src\backend\dao\DBConnection.java
C:\Users\prave\Desktop\HealthTrackerjava\src\backend\dao\DoctorDAO.java
C:\Users\prave\Desktop\HealthTrackerjava\src\backend\dao\PatientDAO.java
C:\Users\prave\Desktop\HealthTrackerjava\src\frontend\admin\AddServiceRecordUI.java
C:\Users\prave\Desktop\HealthTrackerjava\src\frontend\admin\AdminDashboardUI.java
C:\Users\prave\Desktop\HealthTrackerjava\src\frontend\admin\AdminLoginUI.java
C:\Users\prave\Desktop\HealthTrackerjava\src\frontend\common\DataViewerUI.java
C:\Users\prave\Desktop\HealthTrackerjava\src\frontend\common\MainMenuUI.java
C:\Users\prave\Desktop\HealthTrackerjava\src\frontend\common\UITheme.java
C:\Users\prave\Desktop\HealthTrackerjava\src\frontend\doctor\AddHealthRecordUI.java
C:\Users\prave\Desktop\HealthTrackerjava\src\frontend\doctor\DoctorDashboardUI.java
C:\Users\prave\Desktop\HealthTrackerjava\src\frontend\doctor\DoctorLoginUI.java
C:\Users\prave\Desktop\HealthTrackerjava\src\frontend\doctor\DoctorRegistrationUI.java
C:\Users\prave\Desktop\HealthTrackerjava\src\frontend\patient\PatientDashboardUI.java
C:\Users\prave\Desktop\HealthTrackerjava\src\frontend\patient\PatientLoginUI.java
C:\Users\prave\Desktop\HealthTrackerjava\src\frontend\patient\PatientRegistrationUI.java
